name: Validate JSON
on: [push, pull_request]
jobs:
jq-validate:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Validate JSON files
run: |
sudo apt-get update && sudo apt-get install -y jq
for f in $(git ls-files '*.json'); do
echo "Validating $f" && jq empty "$f"
done
