name: Validate JSON
'on':
push:
pull_request:
jobs:
validate:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Validate JSON files
shell: bash
run: |
set -euo pipefail
sudo apt-get update && sudo apt-get install -y jq
mapfile -t files < <(git ls-files '*.json')
if ((${#files[@]} == 0)); then
echo "No JSON files found"; exit 0
fi
for f in "${files[@]}"; do
echo "Validating $f"
jq empty "$f"
done
